server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.fw.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#eureka配置
eureka:
 client:
   service-url:
    defaultZone: http://testEureka1:7001/eureka/,http://testEureka2:7002/eureka/,http://testEureka3:7003/eureka/
 instance:
   instance-id: springcloud-provider-dept-hystrix-8001



#info配置
info:
  app.name: fw-springcloud
  company.name: fw-company
